### ISSUE TITLE
Site gone?

### ISSUE THREAD

**Issue by mnp** [HowNetWorks/uriteller#35]
It looks like the site is gone?

I'm wondering what conclusions were drawn from all the cloudsourced results of leak testing?

So I had the same idea, puttered around, came to the same conclusions, and then found Joachim's blog posts, an HN discussion I've lost now, and maybe a third implementation.

Where I was hoping to go with mine was an ongoing discussion, perhaps on Reddit because they support discussions as well as wiki for keeping results.  I was hoping to engage more people from wider audience at a social level, with the message that "stuff leaks" and "bots sniff".  I think the hard part was communicating this message to them: implementing something like this repo is relatively easy, but explaining it to a grandparent on FB is harder without using words like URI, URL, or link.

Anyway, those are my thoughts, wondering what's the wrapup here?

**Comment by jviide** [comment]
The site is indeed gone. I guess you could say that the wrap-up from our part was to just quietly go into the night. Our Google Cloud credits ran out, and the site wasn't really optimized for cost efficiency :-) As a replacement I'd suggest checking out [Canarytokens](https://canarytokens.org/) and [RequestBin](https://github.com/Runscope/requestbin). RequestBin doesn't have a public instance anymore, but seems to have a way to self-host on Heroku. 

I can't offer any insights about cloudsourced leak testing results: We didn't keep track of how the site was used beyond [basic analytics](https://github.com/HowNetWorks/uriteller/blob/master/src/backend/lib/analytics.js).

I totally agree that the tech itself is simple enough. The hard part is communicating the message as well as how to interpret the results. Turns out that it's easy to get spooked when Private Messenger X *seems* to be leaking link shares, when the culprit is really the Link Shortener Y used to shorten the link before sharing.

Sorry that I didn't have better answers to your questions. From our part URI:teller is done for the foreseeable future. Who knows, maybe someone takes (i.e. forks) the codebase and starts from there - it would indeed be cool to have a living document on how different services leak or don't leak. Perhaps even a GitHub repo would be enough for collecting and presenting the data through a wiki or a GitHub Pages site.

I'll close this issue, but feel free to comment if there's still something to discuss!

**Comment by jviide** [comment]
Oh, and thanks @mnp for reminding that README.md didn't at all mention that the site is down. I added a notice now.

**Comment by mnp** [comment]
Great, thanks for the links and the ideas!
